version: '3.4'

services:

  admin:
    container_name: admin
    build:
      context: ./services/admin
      dockerfile: Dockerfile-dev
    volumes:
      - ./services/admin:/usr/src/app
    ports:
      - 5001:5000
    environment:
      - FLASK_APP=project/__init__.py
      - FLASK_DEBUG=1
      - ENVIRONMENT_TYPE=development
      #- APP_SETTINGS=instance.config.DevelopmentConfig
      #- DEMO_APP_SETTINGS=instance.demoConfig.DevelopmentConfig
